ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

[priorities]
"1" = 1
"2" = 10

[[structure]]
name = "rplacede_schriftzug"
file = "images/rplacede_schriftzug.png"
startx = 0
starty = 856
priority = 2

[[structure]]
name = "flagge"
file = "images/flagge.png"
startx = 0
starty = 830
priority = 1
