[priorities]
"1" = 1
"2" = 2

[[structure]]
name = "maus"
file = "images/maus.png"
startx = 58
starty = 832
priority = 1

[[structure]]
name = "maus2"
file = "images/maus.png"
startx = 258
starty = 832
priority = 1
