name: Run Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Hello World
          run: python scripts/generate_json.py
          shell: sh
       
      - name: Hello World
          run: python scripts/render_json.py
          shell: sh
          
